# config.py

WANTED_CHANNELS = ['PZ', 'PO3', 'PO4', 'PO5', 'PO6', 'POZ', 'OZ', 'O1', 'O2']
NUM_CHANNELS = len(WANTED_CHANNELS)

WINDOW_SIZE = 512
WINDOW_STRIDE = 128

BATCH_SIZE = 32

LATENT_DIM = 12
NOISE_DIM = 24

LR_EMBEDDER = 5e-4
LR_RECOVERY = 1e-3
EPOCHS_EMBEDDER = 150
NUM_LAYERS_RECOVERY = 2
NUM_LAYERS_EMBEDDER = 2

LR_SUPERVISOR = 1e-3
LR_SUPERVISOR_JOINT = 1e-4
EPOCHS_SUPERVISOR = 50
NUM_LAYERS_SUPERVISOR = 1

LR_GENERATOR = 5e-5
LR_DISCRIMINATOR = 5e-5
EPOCHS_JOINT = 250
HIDDEN_DIM_DISCRIMINATOR = 64
HIDDEN_DIM_GENERATOR = 32
NUM_LAYERS_GENERATOR = 3
NUM_LAYERS_DISCRIMINATOR = 3

LAMBDA_SUP = 85
LAMBDA_MOM = 15
LAMBDA_SPEC = 0.2
SUP_LOSS_WINDOW = 10
DISCRIMINATOR_THRESHOLD = 0.1

LR_CLASSIFIER = 1e-3
EPOCHS_CLASSIFIER = 50